# -*- coding: utf-8 -*-
"""Listas y Diccionarios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lQRUkwzx308jCu_maGkrCVZsoyt5Hmou

# Listas y Diccionarios- Tipos de Datos complejos

Datos Simples

Cadenas - Strings

Entero - Int

Decimales - Float

Booleano - True o False

## Datos Complejos
nos permiten almacenar multiples valores a la vez.

listas - Arrays

es una coleccion ordenada de elementos, los cuales puedo modificar, agregar y eliminar

Manzanas, Peras, Leche, Carne, Pollo

Diccionarios - objetos

es una coleccion de datos desordenada almacenada con clave = valor.

Clave   Valor

paula: 3014567898

Pedro: 3105678998

Carlos: 3155874569
"""

#Lista

frutas=["Manzana","Pera","Naranja"]
print(frutas[1]) # Acceder a un elemento de la lista

frutas[2]="Fresa" #Modificar un elemento de la lista
print(frutas[2])

print(*frutas) #Muestra toda la lista de fruta. *quita los simbolos de la lista

frutas.append("Uva") # me permite agreagar un elemento a la lista, en la ultima posicion
print(*frutas)

frutas.pop()# elimina la posicion que uno ingrese de la lista
print(*frutas)

frutas.remove("Pera") #nombre del elemento en especifico que quiero eliminar
print(*frutas)

print(len(frutas)) #Longitud de la lista

asignaturas=["Matematicas","Español","Sociales","Ingles","CienciasN"]
print(asignaturas[1])

asignaturas[2]="Lenguaje"
print(asignaturas[2])

print(*asignaturas)

asignaturas.append("EdFisica")
print(*asignaturas)

# Diccionarios

contactos={
    "Pedro": "318-856-7898",
    "Maria":"315-756-8954",
    "Carlos": "315-523-4574"
}

print("El contacto de Pedro es:",contactos["Pedro"]) #llamo un elemento por medio de su clave

contactos["Camila"]="310-567-7458" # agregando un nuevo contacto al diccionario o modificar el valor de la clave
print(contactos)

contactos["Maria"]="315-456-7834" # modifico el valor de la clave

del contactos["Pedro"]#Eliminar un contacto
print(contactos)

#Crear una lista de tareas, modificarla , eliminar la ultima tarea y agregar una tarea

Tareas=["Mercar","Barrer","Trapear","Ordenarcuarto","Cocinar"]
print(*Tareas)

Tareas[2]="Limpiarpolvo" #Modificar
print(*Tareas)

Tareas.append("Lavarropa") # Agregar
print(*Tareas)

Tareas.pop()# Elimina
print(*Tareas)

#Crear un diccionario, que almacene nombre de productos y sus precios, modificar un precio, agregar un nuevo producto y eliminar un producto

compras={
    "Papa": 5500,
    "Tomates":4000,
    "Carne": 25000,
    "Aceite": 18000
}
print(compras)

compras["Pasta"]=1200 # Agregar
print(compras)

compras["Tomates"]=3000 # modificar
print(compras)

del compras["Aceite"]#Eliminar
print(compras)

contactos={
    "Pedro":{
        "Telefono":[3155678743, 3107562315],
        "Correo":"pedro@gmail.com",
        "Direccion":{
            "Calle":"109",
            "Barrio":"Bochalema",
            "Ciudad":"Cali"
        }
    },
    "Lucia":{
        "Telefono":[3165566652, 3112459315],
        "Correo":"lucia@gmail.com",
        "Direccion":{
            "Calle":"4",
            "Barrio":"Corregimiento Naranjal",
            "Ciudad":"Bolivar"
        }
    },
    "Alejandro":{
        "Telefono":[3203246652, 3116598765],
        "Correo":["Alejoxx@gmail.com", "alejo1209@hotmail.com","AlejoJ@pio.edu"],
        "Direccion":{
            "Calle":"5",
            "Barrio":"Manuela Beltran",
            "Ciudad":"Cali"
        }
    }
}

print(contactos)

contactos["Tatiana"]={
    "Telefono": [3205204653, 3286547865, 3155671209],
    "Correo": "tatiana@gmail.com",
    "Ciudad":"Bolivar"
}

print(*contactos)

print("El telefono de Lucia es: ", contactos["Lucia"]["Telefono"])

print("El segundo telefono de tatiana es: ", contactos["Tatiana"]["Telefono"][1])

print("La ciudad de residencia de Alejandro es: ", contactos["Alejandro"]["Direccion"]["Ciudad"])

CiudadLucia= contactos["Lucia"]["Direccion"]["Ciudad"]
print("La ciudad de Lucia es: ", CiudadLucia)

print(CiudadLucia)

telefonosTatiana= contactos["Tatiana"]["Telefono"]
print(telefonosTatiana)

#for

for telefono in telefonosTatiana:
  print("El numero de tatianan es: ", telefono)


for i, telefono in enumerate (telefonosTatiana, start=1): #enumerate es una funcion que agrega un contador a cada elemento
  print(f"El numero {i} de tatianan es: ", telefono)

  correosalejo= contactos["Alejandro"]["Correo"]

for i, correo in enumerate (correosalejo, start=1):
  print(f"El correo {i} de alejandro es: ", correo)

contactos["Pedro"]["Cumpleaños"]="20 de junio" #agregar una clave nueva o campo nuevo
print("El cumpleaños de Andres es ",contactos["Pedro"])

contactos["Pedro"]["Fecha de nacimiento"]=[20,"junio",1995]
print("La fecha de nacimiento de Pedro es ",*contactos["Pedro"]["Fecha de nacimiento"])

nacimiento=contactos["Pedro"]["Fecha de nacimiento"][2]
print(nacimiento)

nac= nacimiento - 2024

if nac >= 18:
  print ("Es mayor de edad")
else :
  print ("Es menor de edad")

del contactos["Tatiana"] # para eliminar un contacto completo
print(*contactos)

del contactos["Alejandro"]["Correo"][0]
print (contactos["Alejandro"]["Correo"])

contactos["Pedro"]["Telefono"].remove(3107562315)
print(*contactos["Pedro"]["Telefono"])

